// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTrackerPlanerMVC.Models;

namespace TimeTrackerPlanerMVC.Migrations
{
    [DbContext(typeof(TasksContext))]
    [Migration("20180713060637_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("TimeTrackerPlanerMVC.Models.Categories", b =>
                {
                    b.Property<int>("catid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("catname");

                    b.Property<int>("projectid");

                    b.HasKey("catid");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TimeTrackerPlanerMVC.Models.Projects", b =>
                {
                    b.Property<int>("projectid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("projectname");

                    b.HasKey("projectid");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TimeTrackerPlanerMVC.Models.TaskNames", b =>
                {
                    b.Property<int>("taskid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("categoryid");

                    b.Property<string>("taskname");

                    b.HasKey("taskid");

                    b.ToTable("TaskNames");
                });

            modelBuilder.Entity("TimeTrackerPlanerMVC.Models.TasksDoing", b =>
                {
                    b.Property<int>("workid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("duration");

                    b.Property<DateTime>("starttime");

                    b.Property<int>("taskid");

                    b.HasKey("workid");

                    b.ToTable("TasksDoing");
                });

            modelBuilder.Entity("TimeTrackerPlanerMVC.Models.TasksPlanned", b =>
                {
                    b.Property<int>("planid")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("TasksDoingworkid");

                    b.Property<int>("taskid");

                    b.HasKey("planid");

                    b.HasIndex("TasksDoingworkid");

                    b.ToTable("TasksPlanned");
                });

            modelBuilder.Entity("TimeTrackerPlanerMVC.Models.TasksPlanned", b =>
                {
                    b.HasOne("TimeTrackerPlanerMVC.Models.TasksDoing", "TasksDoing")
                        .WithMany("PlannedTasks")
                        .HasForeignKey("TasksDoingworkid");
                });
#pragma warning restore 612, 618
        }
    }
}
